apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::385046010615:role/analytics-irsa-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: prod
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: analytics-sa
      containers:
        - name: analytics
          image: 385046010615.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: AWS_REGION
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: DYNAMODB_TABLE_NAME
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: prod
spec:
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
