apiVersion: v1
kind: ConfigMap
metadata:
  name: video-analytics-config
  namespace: prod
data:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: video-analytics-uploads
  SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/385046010615/video-processing-jobs
  DYNAMODB_TABLE_NAME: video-metadata
---
apiVersion: v1
kind: Secret
metadata:
  name: video-analytics-secrets
  namespace: prod
stringData:
  JWT_SECRET: "b7f4c1e8a2d9f0c6e3b1a7d4f9e2c5b8a1d6e7f3c9b0a4f2d8c3e1b7a9f6d2c4"
