apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::385046010615:role/processor-irsa-role   # to be created after cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: prod
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: processor-sa
      containers:
        - name: processor
          image: 385046010615.dkr.ecr.us-east-1.amazonaws.com/processor-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: AWS_REGION
            - name: SQS_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: SQS_QUEUE_URL
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: DYNAMODB_TABLE_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: prod
spec:
  selector:
    app: processor
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
