apiVersion: v1
kind: ServiceAccount
metadata:
  name: uploader-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::385046010615:role/uploader-irsa-role   # to be created later

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
  namespace: default
  labels:
    app: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: uploader-sa
      containers:
        - name: uploader
          image: 385046010615.dkr.ecr.us-east-1.amazonaws.com/uploader-service:1.0
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_BUCKET_NAME
              value: "video-analytics-uploads"
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/385046010615/video-processing-jobs"
---
apiVersion: v1
kind: Service
metadata:
  name: uploader-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: uploader
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
