apiVersion: v1
kind: ServiceAccount
metadata:
  name: uploader-sa
  namespace: prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::385046010615:role/uploader-irsa-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
  namespace: prod
  labels:
    app: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: uploader-sa
      containers:
        - name: uploader
          image: 385046010615.dkr.ecr.us-east-1.amazonaws.com/uploader-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: AWS_REGION
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: S3_BUCKET_NAME
            - name: SQS_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: video-analytics-config
                  key: SQS_QUEUE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: uploader
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: uploader
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
