apiVersion: v1
kind: Service
metadata:
  name: processor-service
  labels:
    app: processor
spec:
  selector:
    app: processor
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
