apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: analytics
    count: 1
  - name: auth
    count: 1
  - name: gateway
    count: 1
  - name: processor
    count: 1
  - name: uploader
    count: 1
  - name: frontend
    count: 1

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 64Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 128Mi

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=DEBUG

images:
  - name: video-analytics-analytics
    newName: 385046010615.dkr.ecr.us-east-1.amazonaws.com/video-analytics-analytics
    newTag: latest
  - name: video-analytics-auth
    newName: 385046010615.dkr.ecr.us-east-1.amazonaws.com/video-analytics-auth
    newTag: latest
  - name: gateway-service
    newName: 385046010615.dkr.ecr.us-east-1.amazonaws.com/gateway-service
    newTag: latest
  - name: video-analytics-processor
    newName: 385046010615.dkr.ecr.us-east-1.amazonaws.com/video-analytics-processor
    newTag: latest
  - name: video-analytics-uploader
    newName: 385046010615.dkr.ecr.us-east-1.amazonaws.com/video-analytics-uploader
    newTag: latest
  - name: video-analytics-frontend
    newName: 385046010615.dkr.ecr.us-east-1.amazonaws.com/video-analytics-frontend
    newTag: latest
